### ISSUE TITLE
能否增加gcr.io的knative-release同步

### ISSUE THREAD

**Issue by scott-wong** [mritd/gcrsync#11]
您好，最近研究knative，需要的镜像地址是这种：
gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:e738961834f9b696b88d5316cb7c45e6a15e26ccbb78fa79686b2dfd4bceceaf
我尝试fork您的imgsync，发现无法直接使用。能否增加gcr.io的knative-release同步支持，谢谢。

`level=fatal msg="failed to get gcr images, address: https://gcr.io/v2/knative-release/tags/list, error: []string: decode slice: expect [ or n, but found \x00, error found in #0 byte of ...||..., bigger context ...||..."`

**Comment by mritd** [comment]
这个 namespace 下的有点特殊，稍后我处理一下

**Comment by mritd** [comment]
@scott-wong `gcr.io/knative-releases/knative.dev/eventing/cmd` 下的镜像已经全部手动同步完成了，不过自动化还需要等待一段时间，准备为 knative 写一个专门的同步器；经过测试这个 namespace 下的镜像跟其他的都不一样，很尴尬....这种 多级分割 `domain/a/b/c/d:tag` 的格式目前 docker 仓库 好像是不支持的。

**Comment by scott-wong** [comment]
太感谢了，docker确实不支持，我把我需要的knative相关镜像逐个通过阿里云容器服务搞了一下。除了eventing下面的还有serving、net-istio。不过就别手动同步了，期待您的同步器，嘿嘿。

**Comment by mritd** [comment]
@scott-wong 遇到一个很尴尬的问题，没用过这玩意，你只不知道从那能获取到所有 knative 镜像列表？

**Comment by mritd** [comment]
查看 ko 项目，理解其镜像构成格式和扩展语法

refs https://github.com/google/ko

**Comment by mritd** [comment]
😂 似乎捅了马蜂窝

**Comment by scott-wong** [comment]
我也刚接触knative，只有个笨方法在https://github.com/knative 主要几个项目release下yaml文件里找gcr.io开头的。现在访问https://gcr.io/knative-release/tags/list 会报无权限，难道是knative还没1.0，所以不公开。
估计只能按您的方法去了解ko 项目了，不过我不懂go，帮不上忙。。

**Comment by scott-wong** [comment]
@mritd 请教下怎么手动同步呢，比如我想同步gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory 下面所有镜像

**Comment by mritd** [comment]
使用最新的 v2.1.0 pre-releae，执行 `./imgsync_linux_amd64 gcr --namespace knative-releases/knative.dev/eventing/cmd/in_memory --user USER --password PASSWD` 进行同步既可

**Comment by mritd** [comment]
@scott-wong 可以加入 tg 来讨论 https://t.me/imgsync

**Comment by scott-wong** [comment]
太感谢了:D
