### ISSUE TITLE
问一下，这个工具怎么使用的呢？

### ISSUE THREAD

**Issue by lvjing2** [mritd/gcrsync#2]

**Comment by lvjing2** [comment]
GOROOT=/usr/local/Cellar/go/1.11/libexec #gosetup
GOPATH=/Users/youji.zzl/go #gosetup
/usr/local/Cellar/go/1.11/libexec/bin/go build -o /private/var/folders/wh/x3mx8z955_s8n0mc8bp14nhm0000gp/T/___go_build_main_go -gcflags "all=-N -l" /Users/youji.zzl/go/src/github.com/mritd/gcrsync/main.go #gosetup
"/Users/youji.zzl/Library/Application Support/IntelliJIdea2018.2/intellij-go/lib/dlv/mac/dlv" --listen=localhost:57816 --headless=true --api-version=2 --backend=default exec /private/var/folders/wh/x3mx8z955_s8n0mc8bp14nhm0000gp/T/___go_build_main_go -- --githubtoken lvjing2 #gosetup
API server listening at: 127.0.0.1:57816
INFO[0103] Init http client.                            
INFO[0107] Init docker client.                          
INFO[0121] Init limit channel.                          
INFO[0146] Init update channel.                         
INFO[0146] Init commit repo.                            
Cloning into 'gcr'...
remote: Counting objects: 270, done.        
remote: Compressing objects: 100% (91/91), done.        
remote: Total 270 (delta 85), reused 80 (delta 37), pack-reused 141        
Receiving objects: 100% (270/270), 284.33 KiB | 384.00 KiB/s, done.
Resolving deltas: 100% (147/147), done.
INFO[0162] Init success...                              
ERRO[0273] Get https://gcr.io/v2/google-containers/tags/list: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 

Can't get the tags list..

**Comment by mritd** [comment]
文档已更新

**Comment by lvjing2** [comment]
直接从你docker hub的仓库里下载的确方便了很多，谢谢了
