### ISSUE TITLE
我想使用 azure 中国提供的镜像是一个更好的选择

### ISSUE THREAD

**Issue by lizebang** [mritd/gcrsync#4]
@mritd 
下面是 azure 中国的镜像网址：
http://mirror.azure.cn/help/gcr-proxy-cache.html
你可以先测试一下。
我想如果可以，请可以把它加到 README 中，让更多的人受益。

**Comment by mritd** [comment]
ok，稍后我将测试一下速度

**Comment by mritd** [comment]
测试了一下速度很不错，唯一一点暂时不确定: 在某些政治敏感时期各大大学的各种同步镜像源都会停止

不清楚 Azure 在这种时候会不会受到干扰

**Comment by lizebang** [comment]
大的公司都有合法的流量出口途径，但是你的担心不无道理。

**Comment by lizebang** [comment]
@mritd 
如果稳定 azure 的镜像确实要优于 gcrsync + travis-ci 的同步的。
gcrsync 有个缺陷，就是它只比对镜像 tag 并没有对比 hash 值。如果一个镜像只有 latest 一个版本，然后每次最新都只有最新的镜像打上 latest tag，此时 gcrsync 根本发现不了。并且在镜像有漏洞时，官方重新打包了镜像，gcrsync 也无法发现。
而 azure 是用的 docker registry 的 proxy + cache，能保证镜像和 gcr 完全一样。

**Comment by lizebang** [comment]
@mritd 
最后，谢谢你在 README 上与大家一起分享，也感谢你的项目。

**Comment by mritd** [comment]
@lizebang Thank you very much for your suggestion. If there is no problem, I will close this issue. 😉

**Comment by lizebang** [comment]
@mritd Thanks, no problem.

**Comment by mritd** [comment]
@lizebang Where can I report a missing gcr image?  I found that the image could not be pulled by `gcr.azk8s.cn gcr.azk8s.cn/google_containers/storage-provisioner:v1.8.1`

**Comment by lizebang** [comment]
@mritd 抱歉，我在准备考研所以回复的有些晚。你可以尝试联系 osmirror@microsoft.com。我在 http://mirror.azure.cn/ 上找到的联系方式。

**Comment by lizebang** [comment]
我刚刚看了一下这个镜像，storage-provisioner:v1.8.1 这个镜像并不在 google_containers 域下，它由k8s-minikube 维护，所以应该确实是无法拉取的。

**Comment by liangyuanpeng** [comment]
目前 微软中国针对K8S image提供的镜像服务已不再对外提供，真是一个让人沮丧的消息

**Comment by mritd** [comment]
@liangyuanpeng 从哪得到的消息？？？

**Comment by mritd** [comment]
好吧，这个项目准备重启。

**Comment by mritd** [comment]
项目基本重构完成。
