### ISSUE TITLE
增加 gcr.io/google-samples 仓库

### ISSUE THREAD

**Issue by currycan** [mritd/gcrsync#8]
莫佬，
    能不能增加下同步`gcr.io/google-samples`仓库镜像，谢谢！

**Comment by mritd** [comment]
理论上 gcr.io 下所有公开 namespace 的镜像都是支持的，不过我需要测试一下，以及添加对应的 CI

**Comment by mritd** [comment]
程序本身似乎问题不大，添加 ci 应该就可以了 
![image](https://user-images.githubusercontent.com/13043245/80299790-b8fd3680-87c9-11ea-9a06-78b6f118b0d5.png)

**Comment by currycan** [comment]
嗯！谢谢！
azure的镜像仓库用不了了，也就指望莫佬的这个仓库了。
刚刚试着直接拉了一下`gcr.io/google-samples`里的镜像，发现找不到。现在是可以了！

**Comment by currycan** [comment]
另外，`quay.io`的镜像好像也没有全量同步，只有`flannel`的镜像吧？

**Comment by mritd** [comment]
对的 quay.io 镜像很多的，感觉没必要全量同步，后面按需增加同步吧。

**Comment by mritd** [comment]
144 个镜像手动同步完成，其中两个同步失败，具体失败原因后续我补充文档(简单地说是目标镜像本身有问题不规范)；目前等待 CI 自动执行完并且完成 manifests cache。
